server:
  port: 9411

spring:
  application:
    name: amscloud-zipkin
  sleuth:
      enabled: false
##zipkin启动报错无法访问的解决方法
management:
  metrics:
    web:
      server:
        auto-time-requests: false