server:
  port: 8081
spring:
  application:
    name: service-one
  rabbitmq:
    port: 5762
    username: guest
    password: guest
    host: 127.0.0.1
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh